export const data = [
    {
        "id": 1,
        "company": null,
        "title": "Software Engineer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": "80,000 - 100,000 USD per year",
        "required_experience": "2-4 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-03T03:23:27.801399Z",
        "application_deadline": "2024-12-31T23:59:59Z",
        "is_active": true,
        "posted_by": 1,
        "applicants": []
    },
    {
        "id": 2,
        "company": null,
        "title": "Software Engineer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": "80,000 - 100,000 USD per year",
        "required_experience": "2-4 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T08:39:44.706676Z",
        "application_deadline": "2024-12-31T23:59:59Z",
        "is_active": true,
        "posted_by": 1,
        "applicants": []
    },
    {
        "id": 3,
        "company": {
            "id": 1,
            "company_name": "My Company",
            "description": "We are a tech company focusing on innovative solutions.",
            "website": "https://www.mycompany.com",
            "logo": "/pp.jpg",
            "is_active": false,
            "created_at": "2024-12-14T09:24:07.094178Z",
            "updated_at": "2024-12-14T09:28:27.720908Z",
            "employees": []
        },
        "title": "Software Engineer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": "80,000 - 100,000 USD per year",
        "required_experience": "2-4 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T10:10:31.460360Z",
        "application_deadline": "2024-12-31T23:59:59Z",
        "is_active": true,
        "posted_by": 21,
        "applicants": []
    },
    {
        "id": 4,
        "company": null,
        "title": "Software Engineer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": "80,000 - 100,000 USD per year",
        "required_experience": "2-4 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T10:11:28.152990Z",
        "application_deadline": "2024-12-31T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 5,
        "company": null,
        "title": "QA Engineer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": "80,000 - 100,000 USD per year",
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T10:15:23.652411Z",
        "application_deadline": "2024-12-31T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 6,
        "company": null,
        "title": "Frontend Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T12:29:15.757477Z",
        "application_deadline": "2024-12-19T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 7,
        "company": null,
        "title": "Backend Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "New York, NY",
        "job_type": "full-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T12:29:36.849267Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 8,
        "company": null,
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T12:54:00.300344Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 9,
        "company": null,
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T13:01:56.110939Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 21,
        "applicants": []
    },
    {
        "id": 10,
        "company": {
            "id": 1,
            "company_name": "My Company",
            "description": "We are a tech company focusing on innovative solutions.",
            "website": "https://www.mycompany.com",
            "logo": "/pp.jpg",
            "is_active": false,
            "created_at": "2024-12-14T09:24:07.094178Z",
            "updated_at": "2024-12-14T09:28:27.720908Z",
            "employees": []
        },
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T13:02:18.344929Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 21,
        "applicants": []
    },
    {
        "id": 11,
        "company": {
            "id": 1,
            "company_name": "My Company",
            "description": "We are a tech company focusing on innovative solutions.",
            "website": "https://www.mycompany.com",
            "logo": "/pp.jpg",
            "is_active": false,
            "created_at": "2024-12-14T09:24:07.094178Z",
            "updated_at": "2024-12-14T09:28:27.720908Z",
            "employees": []
        },
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T13:04:53.736427Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 21,
        "applicants": []
    },
    {
        "id": 12,
        "company": null,
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T13:08:58.383210Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 15,
        "applicants": []
    },
    {
        "id": 13,
        "company": {
            "id": 1,
            "company_name": "My Company",
            "description": "We are a tech company focusing on innovative solutions.",
            "website": "https://www.mycompany.com",
            "logo": "/pp.jpg",
            "is_active": false,
            "created_at": "2024-12-14T09:24:07.094178Z",
            "updated_at": "2024-12-14T09:28:27.720908Z",
            "employees": []
        },
        "title": "Software Developer",
        "description": "We are looking for a skilled Software Engineer to join our team.",
        "location": "sanepa",
        "job_type": "part-time",
        "salary": null,
        "required_experience": "4-5 years",
        "skills_required": "Python, Django, REST API, Docker",
        "education_level": "Bachelor's Degree in Computer Science or related field",
        "job_level": "entry",
        "shift": "day",
        "posted_at": "2024-12-14T13:09:05.465776Z",
        "application_deadline": "2024-12-14T23:59:59Z",
        "is_active": true,
        "posted_by": 21,
        "applicants": []
    }
]